worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;
    include /etc/nginx/mime.types;

    server {
        listen 80;

        # STATIC NEXT.JS FILES
        location /_next/ {
            alias /var/www/html/frontend/.next/;
        }

        # API routes → Laravel
        location /api {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Laravel PHP handling
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
            include fastcgi_params;
        }

        # FRONTEND → Next.js SSR
        location / {
            root /var/www/html/frontend;
            try_files $uri @nextjs;
        }

        location @nextjs {
            proxy_pass http://127.0.0.1:3000;
        }
    }
}
